"""Lifecycle event names used by runtime."""

RUN_REQUESTED = "run.requested"
RUN_VALIDATED = "run.validated"
SESSION_ACQUIRED = "session.acquired"
CONTEXT_CREATED = "context.created"
MEMORY_INJECTED = "memory.injected"
MEMORY_INJECT_FAILED = "memory.inject_failed"
PATTERN_STEP_STARTED = "pattern.step_started"
PATTERN_STEP_FINISHED = "pattern.step_finished"
MEMORY_WRITEBACK_SUCCEEDED = "memory.writeback_succeeded"
MEMORY_WRITEBACK_FAILED = "memory.writeback_failed"
RUN_COMPLETED = "run.completed"
RUN_FAILED = "run.failed"

